console.log('1)', 30 * 5)
console.log('2)', 30 + "7") 
console.log('3)', '30' - "7")
console.log('4)', 40 - true)
console.log('5)', '8' > 8)
console.log('6)', '11' >= '5')
console.log('7)', 'abc' <= 'abs')
console.log('8)', 'abc' > 7)
console.log('9)', 'abc' >= '7')
console.log('10)', true > false)

const a = prompt ("Какое число возвести в квадрат?", 5)
alert (`Квадарат заданного числа равен ` + a*a)